# $FreeBSD$

PORTNAME=	run-one
PORTVERSION=	0.1.0
CATEGORIES=	sysutils

MAINTAINER=	tom@hur.st
COMMENT=	Run a single instance of a command

LICENSE=	MIT

USE_GITHUB=	yes
GH_ACCOUNT=	Freaky
GH_TAGNAME=	d268032811e82ebbd0a1ede13f91a5114fe0357a

PLIST_FILES=	bin/run-one \
		bin/run-this-one \
		bin/run-one-constantly \
		bin/run-one-until-success \
		bin/run-one-until-failure \
		man/man1/run-one.1.gz \
		man/man1/run-this-one.1.gz \
		man/man1/run-one-constantly.1.gz \
		man/man1/run-one-until-success.1.gz \
		man/man1/run-one-until-failure.1.gz

.include <bsd.port.mk>
